In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("../music_data.csv")

In [5]:
df.shape

(99584, 35)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99584 entries, 0 to 99583
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Unnamed: 0                            99584 non-null  int64
 1   bpm                                   99584 non-null  float64
 2   bpm_histogram_first_peak_bpm_mean     99584 non-null  float64
 3   bpm_histogram_first_peak_bpm_median   99584 non-null  float64
 4   bpm_histogram_second_peak_bpm_mean    99584 non-null  float64
 5   bpm_histogram_second_peak_bpm_median  99584 non-null  float64
 6   danceability                          99584 non-null  float64
 7   onset_rate                            99584 non-null  float64
 8   average_loudness                      99584 non-null  float64
 9   dynamic_complexity                    99584 non-null  float64
 10  mfcc_zero_mean                        99584 non-null  float64
 11  tuning_frequency                      99584 non-null  float64
 12  tuning_equal_tempered_deviation       99584 non-null  float64
 13  key_key                               99584 non-null  str
 14  key_scale                             99584 non-null  int64
 15  mood_happy_prob                       99584 non-null  float64
 16  mood_aggressive_prob                  99584 non-null  float64
 17  mood_happy                            99584 non-null  int64
 18  mood_sad                              99584 non-null  int64
 19  mood_relaxed                          99584 non-null  int64
 20  mood_aggressive                       99584 non-null  int64
 21  mood_acoustic                         99584 non-null  int64
 22  mood_electronic                       99584 non-null  int64
 23  mood_party                            99584 non-null  int64
 24  voice_gender                          99584 non-null  int64
 25  timbre                                99584 non-null  int64
 26  tonal_atonal                          99584 non-null  int64
 27  voice_instrumental                    99584 non-null  int64
 28  release_name                          99584 non-null  str
 29  recording_name                        99584 non-null  str
 30  language                              99584 non-null  float64
 31  release_year                          99584 non-null  float64
 32  artist_name                           99434 non-null  str
 33  main_genre                            99584 non-null  str
 34  sub_genre                             99584 non-null  str
dtypes: float64(16), int64(13), str(6)
memory usage: 32.7 MB

In [7]:
df.head()

,Unnamed: 0,bpm,bpm_histogram_first_peak_bpm_mean,bpm_histogram_first_peak_bpm_median,bpm_histogram_second_peak_bpm_mean,bpm_histogram_second_peak_bpm_median,danceability,onset_rate,average_loudness,dynamic_complexity,...,timbre,tonal_atonal,voice_instrumental,release_name,recording_name,language,release_year,artist_name,main_genre,sub_genre
0,0,132.114716,133.0,133.0,117.0,117.0,0.963751,2.697139,0.939739,2.026948,...,0,0,1,Excavated for Evisceration,Fields of Famine,120.0,2018.0,scorched,Metal,death metal
1,1,95.068558,96.0,96.0,88.0,88.0,1.064906,2.686261,0.687424,3.005937,...,1,1,1,The Theory of Everything,Mirror of Dreams,120.0,2013.0,ayreon,Metal,progressive metal
2,2,97.024086,98.0,98.0,91.0,91.0,1.348803,3.769673,0.948725,2.141814,...,0,1,0,Weckt die Toten!,Como Poden,284.0,1998.0,in extremo,Other,Other
3,4,144.950623,144.0,144.0,167.0,167.0,1.575546,4.456016,0.931662,2.811386,...,1,0,0,"Remix Romance, Volume 1",He Keeps Me Alive (Skatebård remix),120.0,2008.0,sally shapiro,Electronic,electronic
4,5,90.576309,98.0,98.0,92.0,92.0,1.127421,4.016946,0.605463,4.058333,...,1,0,0,I Am Three,Pedal Point Blues,120.0,2005.0,mingus big band,Jazz,jazz

Drop columns I don't need

In [8]:
df.drop(columns=['Unnamed: 0', 'tuning_frequency', 'tuning_equal_tempered_deviation', 'language', 'sub_genre',
                 'bpm_histogram_first_peak_bpm_mean', 'bpm_histogram_first_peak_bpm_median',
                 'bpm_histogram_second_peak_bpm_mean', 'bpm_histogram_second_peak_bpm_median'], inplace=True)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99584 entries, 0 to 99583
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   bpm                   99584 non-null  float64
 1   danceability          99584 non-null  float64
 2   onset_rate            99584 non-null  float64
 3   average_loudness      99584 non-null  float64
 4   dynamic_complexity    99584 non-null  float64
 5   mfcc_zero_mean        99584 non-null  float64
 6   key_key               99584 non-null  str
 7   key_scale             99584 non-null  int64
 8   mood_happy_prob       99584 non-null  float64
 9   mood_aggressive_prob  99584 non-null  float64
 10  mood_happy            99584 non-null  int64
 11  mood_sad              99584 non-null  int64
 12  mood_relaxed          99584 non-null  int64
 13  mood_aggressive       99584 non-null  int64
 14  mood_acoustic         99584 non-null  int64
 15  mood_electronic       99584 non-null  int64
 16  mood_party            99584 non-null  int64
 17  voice_gender          99584 non-null  int64
 18  timbre                99584 non-null  int64
 19  tonal_atonal          99584 non-null  int64
 20  voice_instrumental    99584 non-null  int64
 21  release_name          99584 non-null  str
 22  recording_name        99584 non-null  str
 23  release_year          99584 non-null  float64
 24  artist_name           99434 non-null  str
 25  main_genre            99584 non-null  str
dtypes: float64(9), int64(12), str(5)
memory usage: 25.2 MB

Add decade column

In [10]:
df["decade"] = (df["release_year"] // 10 * 10).astype(int).astype(str) + "s"

In [11]:
df.head()

,bpm,danceability,onset_rate,average_loudness,dynamic_complexity,mfcc_zero_mean,key_key,key_scale,mood_happy_prob,mood_aggressive_prob,...,voice_gender,timbre,tonal_atonal,voice_instrumental,release_name,recording_name,release_year,artist_name,main_genre,decade
0,132.114716,0.963751,2.697139,0.939739,2.026948,-601.399475,D,0,0.913683,0.913900,...,1,0,0,1,Excavated for Evisceration,Fields of Famine,2018.0,scorched,Metal,2010s
1,95.068558,1.064906,2.686261,0.687424,3.005937,-683.606689,D,0,0.445709,0.898966,...,1,1,1,1,The Theory of Everything,Mirror of Dreams,2013.0,ayreon,Metal,2010s
2,97.024086,1.348803,3.769673,0.948725,2.141814,-612.465271,A,0,0.176921,1.000000,...,0,0,1,0,Weckt die Toten!,Como Poden,1998.0,in extremo,Other,1990s
3,144.950623,1.575546,4.456016,0.931662,2.811386,-671.900146,A#,1,0.133223,0.880046,...,1,1,0,0,"Remix Romance, Volume 1",He Keeps Me Alive (Skatebård remix),2008.0,sally shapiro,Electronic,2000s
4,90.576309,1.127421,4.016946,0.605463,4.058333,-671.903320,D#,1,0.218376,0.600825,...,1,1,0,0,I Am Three,Pedal Point Blues,2005.0,mingus big band,Jazz,2000s

In [12]:
df['decade'].value_counts()

decade
2010s    40774
2000s    25910
1990s    14795
2020s     8049
1980s     4780
1970s     3085
1960s     1721
1950s      418
1930s       28
1940s       24
Name: count, dtype: int64

Clean the release_name and recording_name features

In [13]:
df['main_genre'].value_counts()

main_genre
Rock                20610
Other               18240
Electronic          17714
Pop                  7970
Metal                6632
Jazz                 5281
Classical            4249
Hip Hop              3806
Punk                 2909
Folk                 2384
Soundtrack           2054
Country              2043
Reggae               1589
Blues                1376
Experimental         1231
R&B                   653
Easy Listening        376
Alternative Rock      235
Dance                 104
Techno                 71
Ambient                35
Soul                   11
Indie Rock              7
Heavy Metal             4
Name: count, dtype: int64

In [14]:
df['release_name'].value_counts()

release_name
II                                               46
III                                              43
Demo                                             34
Live                                             33
Greatest Hits                                    31
                                                 ..
The Curse That Is                                 1
소나기                                               1
Regreso a Casa                                    1
100% Charlie Brown Jr: Abalando a sua fábrica     1
Leaf                                              1
Name: count, Length: 80298, dtype: int64

In [15]:
df['recording_name'].value_counts()

recording_name
Intro                                                                              139
[untitled]                                                                          34
Home                                                                                31
Outro                                                                               29
Interlude                                                                           23
                                                                                  ...
채워보자                                                                                 1
Fortaleza                                                                            1
Quebra-mar                                                                           1
Under Nymånen                                                                        1
Eugene Onegin, Act III: Scene 1: No. 19, Polonaise (Moderato. Tempo di polacca)      1
Name: count, Length: 89836, dtype: int64

Clean release_name

In [16]:
df = df[~df['release_name'].str.startswith('[')]

In [17]:
from pypinyin import pinyin, Style

# Convert Chinese characters to Pinyin
df['release_name'] = df['release_name'].apply(lambda x: ''.join([p[0] for p in pinyin(x, style=Style.NORMAL)]) if isinstance(x, str) else x)

In [18]:
from korean_romanizer.romanizer import Romanizer

def korean_to_romanized(text):
    """
    Convert Korean Hangul to Romanized Latin text.
    """
    if isinstance(text, str):
        return Romanizer(text).romanize()
    return text

# Convert Korean artist names or song names
df['release_name'] = df['release_name'].apply(korean_to_romanized)

In [19]:
import pykakasi

kakasi = pykakasi.kakasi()

def japanese_to_romanized(text):
    """
    Convert Japanese text (Kanji, Hiragana, Katakana) into Romanized Latin text.
    """
    if isinstance(text, str):
        result = kakasi.convert(text)
        return ''.join([item['hepburn'] for item in result])
    return text

# Convert Japanese artist or song names
df['release_name'] = df['release_name'].apply(japanese_to_romanized)

In [20]:
df['release_name'] = df['release_name'].str.lower()

In [21]:
import unicodedata

def remove_diacritics(text):
    """
    Normalize characters with diacritics (e.g., ñ, é) by converting them to basic Latin equivalents (e.g., n, e).
    """
    if isinstance(text, str):
        text = unicodedata.normalize('NFKD', text)  # Normalize to decomposed Unicode (NFKD form)
        return ''.join(c for c in text if not unicodedata.combining(c))  # Remove combining marks
    return text

# Apply the function to clean artist names and other text fields
df['release_name'] = df['release_name'].apply(remove_diacritics)

In [22]:
import re

# Remove non-alphanumeric characters
def clean_text(text):
    if isinstance(text, str):
        text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Keep only alphanumeric and spaces
        return text.strip()
    return text

# Apply the cleaning to text-based features
df['release_name'] = df['release_name'].apply(clean_text)

In [23]:
pd.set_option('display.max_rows', 500)

In [24]:
from itables import show

In [25]:
df['release_name'].value_counts()

release_name
                                               91
ii                                             48
iii                                            48
live                                           44
demo                                           38
                                               ..
the curse that is                               1
sonagi                                          1
regreso a casa                                  1
100 charlie brown jr abalando a sua fabrica     1
leaf                                            1
Name: count, Length: 79264, dtype: int64

Cleaning recording_name

In [26]:


df = df[~df['recording_name'].str.startswith('[')]

from pypinyin import pinyin, Style

# Convert Chinese characters to Pinyin
df['recording_name'] = df['recording_name'].apply(lambda x: ''.join([p[0] for p in pinyin(x, style=Style.NORMAL)]) if isinstance(x, str) else x)

from korean_romanizer.romanizer import Romanizer

def korean_to_romanized(text):
    """
    Convert Korean Hangul to Romanized Latin text.
    """
    if isinstance(text, str):
        return Romanizer(text).romanize()
    return text

# Convert Korean artist names or song names
df['recording_name'] = df['recording_name'].apply(korean_to_romanized)

import pykakasi

kakasi = pykakasi.kakasi()

def japanese_to_romanized(text):
    """
    Convert Japanese text (Kanji, Hiragana, Katakana) into Romanized Latin text.
    """
    if isinstance(text, str):
        result = kakasi.convert(text)
        return ''.join([item['hepburn'] for item in result])
    return text

# Convert Japanese artist or song names
df['recording_name'] = df['recording_name'].apply(japanese_to_romanized)

df['recording_name'] = df['recording_name'].str.lower()

import unicodedata

def remove_diacritics(text):
    """
    Normalize characters with diacritics (e.g., ñ, é) by converting them to basic Latin equivalents (e.g., n, e).
    """
    if isinstance(text, str):
        text = unicodedata.normalize('NFKD', text)  # Normalize to decomposed Unicode (NFKD form)
        return ''.join(c for c in text if not unicodedata.combining(c))  # Remove combining marks
    return text

# Apply the function to clean artist names and other text fields
df['recording_name'] = df['recording_name'].apply(remove_diacritics)

import re

# Remove non-alphanumeric characters
def clean_text(text):
    if isinstance(text, str):
        text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Keep only alphanumeric and spaces
        return text.strip()
    return text

# Apply the cleaning to text-based features
df['recording_name'] = df['recording_name'].apply(clean_text)

In [27]:
df['recording_name'].value_counts()

recording_name
intro                                                                      140
                                                                            79
home                                                                        32
outro                                                                       31
interlude                                                                   24
                                                                          ...
chaewoboja                                                                   1
fortaleza                                                                    1
quebramar                                                                    1
under nymanen                                                                1
eugene onegin act iii scene 1 no 19 polonaise moderato tempo di polacca      1
Name: count, Length: 88572, dtype: int64

In [28]:
df.to_csv("data/music_data_for_rag_cleaned.csv", index=False)